### PR TITLE
Add debounce node

### PR DESCRIPTION
**Pull request by fakob**
The node has all parameters the lodash debounce function has.
If you change the parameters, you need to call the update trigger. This creates a new debounce function with the new values. Having to press the update trigger button is not very elegant, but I was not sure how else to do this.

Screenshot 2022-12-03 at 22 34 16

### CODE REVIEW

**Comment by magnificus** [comment]
Im pretty sure you can do this with a dynamic enum and then not having to use the onAdded function, but will approve nonetheless

**Review by magnificus — APPROVED** [review]
comment

**Comment by fakob** [comment]
Not sure how to use the dynamic enum in this case.
The issue I am trying to solve is to only update the debounce function if some of the input parameters change (wait, maxWait, leading, trailing).

However, regardless of this, I still need to initialise the debounce function once
* for a newly added node (onNodeAdded)
* for a loaded node (onConfigure) -> see updated PR

**Comment by fakob** [comment]
> couldnt you just initialize it the first time it is executed?
ah sure. that is a good idea.
Done

**Pull request merged**
