### PR TITLE
attempt remove loadedgraphid

### PR DESCRIPTION
**Pull request by magnificus**

### CODE REVIEW

**Review by fakob — COMMENTED** [review]
The loadedGraphId was used to load the correct/last graph you were on, when opening the browser. How is this now solved, if it is not stored in the database?

Screenshot 2023-03-20 at 22 54 07

**Comment by magnificus** [comment]
> The loadedGraphId was used to load the correct/last graph you were on, when opening the browser. How is this now solved, if it is not stored in the database?
> 
> Screenshot 2023-03-20 at 22 54 07

was thinking we'd just use the date to open the last modified one, thoughts?

**Comment by magnificus** [comment]
That is the default behaviour and seems to work

**Comment by fakob** [comment]
Ok, sounds good.

**Pull request merged**
