### PR TITLE
only certain options in dropdown

### PR DESCRIPTION
**Pull request by magnificus**

### CODE REVIEW

**Review by fakob — APPROVED** [review]
Looks good.

With the Filetype, I am a bit unsure as it outputs a string (this might change in the future). There might be the corner case of using this in a custom function. This would be an advanced handling though.
Would it be possible to hide the overflow menu and disable the button, in case the type is not part of the list?

Screenshot 2023-11-09 at 21 26 13

**Comment by fakob** [comment]
But I guess the same advanced programming concern would be valid for the other types?

**Comment by magnificus** [comment]
yes, an advanced menu could make sense

**Comment by magnificus** [comment]
With filetype, does that mean you would like it part of the dropdown options?

**Pull request merged**
